package com.company;

public class EvenFibonacciNumbers {

    /*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */

    private static final long MAX = 4000000;

    public static void main(String[] args) {

        int first = 1;
        int second = 2;

        long sum = 2;

        while (true){
            int temp = first + second;

            if(temp > MAX){
                break;
            }

            if((temp & 1) == 0){
                sum += temp;
            }

            first = second;
            second = temp;
        }

        System.out.println(sum);
    }
}
